### ISSUE TITLE
Problem with sessions view

### ISSUE THREAD

**Issue by bilsch** [rubycentral/cfp-app#50]
Not sure where else to ask for help on this.

We are using the cfpapp for our event and having a problem. I populated the event with a track and sessions/rooms but for some reason I'm getting 500 server errors if I try to go in/look around. 

My guess is that I did not populate some piece of information but I have not yet found the missing piece. Any ideas?

```
2015-07-27T17:42:47.991210+00:00 app[web.1]: Started GET "/organizer/events/1/sessions" for 50.58.105.131 at 2015-07-27 17:42:47 +0000
2015-07-27T17:42:48.004908+00:00 app[web.1]: Processing by Organizer::SessionsController#index as HTML
2015-07-27T17:42:48.004912+00:00 app[web.1]:   Parameters: {"event_id"=>"1"}
2015-07-27T17:42:49.059940+00:00 app[web.1]:   Rendered organizer/sessions/_sessions.html.haml (893.3ms)
2015-07-27T17:42:49.306471+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (205.0ms)
2015-07-27T17:42:49.483552+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (154.7ms)
2015-07-27T17:42:49.633074+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (143.5ms)
2015-07-27T17:42:49.779610+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (26.2ms)
2015-07-27T17:42:49.752284+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (118.0ms)
2015-07-27T17:42:49.850205+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (69.8ms)
2015-07-27T17:42:49.942757+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (62.9ms)
2015-07-27T17:42:49.942843+00:00 app[web.1]:   Rendered organizer/rooms/_room.html.haml (842.3ms)
2015-07-27T17:42:50.064969+00:00 app[web.1]:   Rendered organizer/rooms/_form.html.haml (121.6ms)
2015-07-27T17:42:50.065084+00:00 app[web.1]:   Rendered organizer/sessions/_rooms.html.haml (991.7ms)
2015-07-27T17:42:50.082145+00:00 app[web.1]:   Rendered organizer/tracks/_track.html.haml (3.2ms)
2015-07-27T17:42:50.083602+00:00 app[web.1]:   Rendered organizer/sessions/_tracks.html.haml (18.2ms)
2015-07-27T17:42:50.083129+00:00 app[web.1]:   Rendered organizer/tracks/_form.html.haml (0.6ms)
2015-07-27T17:42:50.553803+00:00 app[web.1]:   Rendered shared/schedule/_days.html.haml (458.9ms)
2015-07-27T17:42:50.571146+00:00 app[web.1]:   Rendered organizer/sessions/index.html.haml within layouts/application (2513.2ms)
2015-07-27T17:42:50.575477+00:00 app[web.1]:
2015-07-27T17:42:50.575482+00:00 app[web.1]:     18:           - session = time_slot.conference_wide_session.decorate
2015-07-27T17:42:50.575481+00:00 app[web.1]: ActionView::Template::Error (no implicit conversion of nil into String):
2015-07-27T17:42:50.575484+00:00 app[web.1]:     19:           %td.proposal-slot.session-slot{ colspan: @rooms.count, data: session.cell_data_attr}
2015-07-27T17:42:50.575486+00:00 app[web.1]:     20:             %p
2015-07-27T17:42:50.575487+00:00 app[web.1]:     21:               = session.conference_wide_title
2015-07-27T17:42:50.575488+00:00 app[web.1]:     22:         - else
2015-07-27T17:42:50.575490+00:00 app[web.1]:     23:           - time_slot.sessions.each_with_index do |session, i|
2015-07-27T17:42:50.575491+00:00 app[web.1]:     24:             - if conference_day.session_empty?(session, i, time_slot)
2015-07-27T17:42:50.575492+00:00 app[web.1]:   app/decorators/session_decorator.rb:104:in `+'
2015-07-27T17:42:50.575494+00:00 app[web.1]:   app/decorators/session_decorator.rb:104:in `conference_wide_title'
2015-07-27T17:42:50.575496+00:00 app[web.1]:   app/views/shared/schedule/_days.html.haml:21:in `block in _app_views_shared_schedule__days_html_haml___4579081771853580640_69849383289300'
2015-07-27T17:42:50.575502+00:00 app[web.1]:   app/views/organizer/sessions/_schedule.html.haml:23:in `_app_views_organizer_sessions__schedule_html_haml___587785780559795098_69849383840440'
2015-07-27T17:42:50.575499+00:00 app[web.1]:   app/views/shared/schedule/_days.html.haml:12:in `_app_views_shared_schedule__days_html_haml___4579081771853580640_69849383289300'
2015-07-27T17:42:50.575521+00:00 app[web.1]:
2015-07-27T17:42:50.575497+00:00 app[web.1]:   app/views/shared/schedule/_days.html.haml:12:in `each'
2015-07-27T17:42:50.575505+00:00 app[web.1]:   app/controllers/organizer/sessions_controller.rb:25:in `index'
2015-07-27T17:42:50.575503+00:00 app[web.1]:   app/views/organizer/sessions/index.html.haml:27:in `_app_views_organizer_sessions_index_html_haml__3045360657512574570_69849364900960'
2015-07-27T17:42:50.602929+00:00 app[web.1]: Processing by ErrorsController#internal_error as HTML
2015-07-27T17:42:50.575523+00:00 app[web.1]:
2015-07-27T17:42:50.617053+00:00 app[web.1]:   Rendered errors/internal_error.html.haml within layouts/application (0.2ms)
2015-07-27T17:42:50.567504+00:00 app[web.1]:   Rendered organizer/sessions/_schedule.html.haml (483.8ms)
2015-07-27T17:42:50.572783+00:00 app[web.1]: Completed 500 Internal Server Error in 2568ms
2015-07-27T17:42:50.613587+00:00 app[web.1]:   Parameters: {"event_id"=>"1"}
2015-07-27T17:42:50.809277+00:00 app[web.1]: Completed 500 Internal Server Error in 193ms (Views: 121.3ms | ActiveRecord: 71.5ms)
```

**Comment by bilsch** [comment]
Manually deleting all sessions has 'fixed' the issue for now.

```
sessions = Session.find_each
sessions.each do |s|
Session.delete(s.id)
end
```

Question I have is why. 

```
irb(main):073:0> sessions
=> #<Enumerator: #<ActiveRecord::Relation [#<Session id: 7, conference_day: 1, start_time: "2000-01-01 08:00:00", end_time: "2000-01-01 09:00:00", title: "Registration, Breakfast, and Sponsor Booths Open", description: "", presenter: "", room_id: 7, track_id: nil, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:44:16", updated_at: "2015-07-15 20:44:16">, #<Session id: 8, conference_day: 1, start_time: "2000-01-01 09:15:00", end_time: "2000-01-01 23:00:00", title: "Opening Welcome", description: "", presenter: "", room_id: 1, track_id: 1, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:44:47", updated_at: "2015-07-15 20:44:47">, #<Session id: 9, conference_day: 1, start_time: "2000-01-01 09:15:00", end_time: "2000-01-01 09:45:00", title: "Opening Keynote", description: "", presenter: "", room_id: 1, track_id: nil, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:45:32", updated_at: "2015-07-15 20:45:32">, #<Session id: 10, conference_day: 1, start_time: "2000-01-01 09:45:00", end_time: "2000-01-01 09:55:00", title: "Sponsors", description: "", presenter: "", room_id: 1, track_id: nil, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:45:59", updated_at: "2015-07-15 20:45:59">, #<Session id: 11, conference_day: 1, start_time: "2000-01-01 09:55:00", end_time: "2000-01-01 10:25:00", title: "Talk 1", description: "", presenter: "", room_id: 1, track_id: 1, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:46:40", updated_at: "2015-07-15 20:46:40">, #<Session id: 12, conference_day: 1, start_time: "2000-01-01 10:25:00", end_time: "2000-01-01 10:40:00", title: "Break", description: "", presenter: "", room_id: nil, track_id: nil, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:47:10", updated_at: "2015-07-15 20:47:10">, #<Session id: 13, conference_day: 1, start_time: "2000-01-01 10:40:00", end_time: "2000-01-01 11:10:00", title: "Talk 2", description: "", presenter: "", room_id: 1, track_id: 1, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:47:45", updated_at: "2015-07-15 20:47:45">, #<Session id: 14, conference_day: 1, start_time: "2000-01-01 11:20:00", end_time: "2000-01-01 11:50:00", title: "Talk 3", description: "", presenter: "", room_id: 1, track_id: 1, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:48:46", updated_at: "2015-07-15 20:48:46">, #<Session id: 15, conference_day: 1, start_time: "2000-01-01 11:50:00", end_time: "2000-01-01 01:50:00", title: "Lunch", description: "", presenter: "", room_id: 1, track_id: 1, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:49:03", updated_at: "2015-07-15 20:49:03">, #<Session id: 16, conference_day: 1, start_time: "2000-01-01 13:00:00", end_time: "2000-01-01 13:30:00", title: "Ignites", description: "", presenter: "", room_id: 1, track_id: nil, proposal_id: nil, event_id: 1, created_at: "2015-07-15 20:49:35", updated_at: "2015-07-15 20:49:35">, ...]>:find_each({})>
```

I had pre-populated the sessions without presenters. Not sure if that helps or not...

**Comment by mghaught** [comment]
I haven't dived into the code yet but at first glance this is touching some new functionality that we recently added for RailsConf.  It's very likely that the code doesn't gracefully handle sessions that are missing data.  You should be able to create sessions that don't have all the data fields filled out.  We will be revisiting this code by September for RubyConf so by then we'll get it addressed.  I'll happily look over a PR if you have a fix already.

**Comment by mghaught** [comment]
Just to follow up on this, we've got some new improvements in this area and that should fix it going forward. Please open a new issue if you have the problem again.
